### ISSUE TITLE
Questions about the training process

### ISSUE THREAD

**Issue by Fyzjym** [ecnuycxie/DG-Font#14]
# Questions about the training process
Hello, during the training process, when epoch[2 / 250] 100% is reached, the training did not continue. In the result folder, character images are continuously generated, which takes a lot of time. Duration of this process: 9.2~17:00-now.
May I ask if this is normal?
In addition, is it convenient to inform you of your GPU information and the total training time?
# log

Epoch: [2/250] [900/1000] MODE[GAN_EMA] Avg Loss: D[2.04] G[0.03]
100%|████████████████████████████████████████████████████████████████████████████████▉| 999/1000 [34:33<00:02,  2.08s/it]Epoch: [2/250] [1000/1000] MODE[GAN_EMA] Avg Loss: D[2.03] G[0.04]
100%|████████████████████████████████████████████████████████████████████████████████| 1000/1000 [34:35<00:00,  2.08s/it]

Now, there is no output in the terminal.
In the result file, images are continuously generated.

**Comment by ecnuycxie** [comment]
please check validation.py.  The total training takes nearly 2 days using two 2080Ti.

**Comment by Fyzjym** [comment]
Thanks for your reply.
In the last day (9.4-9.6), I deleted the code of the image saved in the validation.py file to avoid the impact of system IO operations.
However, this method is useless. Training time: 1 epoch takes one day.
Can you give some specific directions for inspection, thank you very much.
# GPU info
Tesla P40

# command
python main.py --gpu 2 --img_size 80 --data_path data --output_k 400 --batch_size 32 --val_num 190

# code change
## validation.py source code 
vutils.save_image(x_res_ema, os.path.join(args.res_dir, '{}_EMA_{}_{}{}.jpg'.format(args.gpu, epoch+1, src_idx, ref_idx)), normalize=True,nrow=(x_res_ema.size(0) // (x_src.size(0) + 2) + 1))
vutils.save_image(x_rnd_ema, os.path.join(args.res_dir, '{}_RNDEMA_{}_{}{}.jpg'.format(args.gpu, epoch+1, src_idx, ref_idx)), normalize=True,nrow=(x_res_ema.size(0) // (x_src.size(0) + 2) + 1))
## validation.py change code 
#vutils.save_image(x_res_ema, os.path.join(args.res_dir, '{}_EMA_{}_{}{}.jpg'.format(args.gpu, epoch+1, src_idx, ref_idx)), normalize=True,nrow=(x_res_ema.size(0) // (x_src.size(0) + 2) + 1))
#vutils.save_image(x_rnd_ema, os.path.join(args.res_dir, '{}_RNDEMA_{}_{}{}.jpg'.format(args.gpu, epoch+1, src_idx, ref_idx)), normalize=True,nrow=(x_res_ema.size(0) // (x_src.size(0) + 2) + 1))

**Comment by Fyzjym** [comment]
No matter what, thank you so much for u relpy and u paper.

**Comment by zengxiaogui2021** [comment]
> No matter what, thank you so much for u relpy and u paper.

**Comment by zengxiaogui2021** [comment]
> No matter what, thank you so much for u relpy and u paper.
I have this situation that epoch to 2 but the process don't continue

**Comment by Fyzjym** [comment]
> > No matter what, thank you so much for u relpy and u paper.
> > I have this situation that epoch to 2 but the process don't continue

bro，Please check your result file, this time should verify and generate image. This process takes a lot of time, and there is no output in the terminal.

**Comment by zengxiaogui2021** [comment]
Thanks！

**Comment by Note-Liu** [comment]
I meet the same problem ，how to speed up training？
