### ISSUE TITLE
Epochs or styles(fonts)? Which factor is more important for the model performance?

### ISSUE THREAD

**Issue by blackpill** [ecnuycxie/DG-Font#17]
If we wanna get better performance for unseen fonts generation, what we should do when training the model?

Is it helpful when we increase the number of training styles?

How many epochs we should train at least?

**Comment by ecnuycxie** [comment]
Increasing the number of training styles does help produce invisible styles, but it is not the perfect solution. In fact, we are still conducting some experiments to improve the performance of generating unseen patterns.
