### ISSUE TITLE
Question about  fig.7 in paper

### ISSUE THREAD

**Issue by Fyzjym** [ecnuycxie/DG-Font#22]
Hi,sir. I have the same question with #6.
But to be honest, I don't understand how this picture is implemented... I'm very sorry, can you elaborate on the implementation details... or are there any examples.
Thanks for reading

**Comment by ecnuycxie** [comment]
Hello, you can follow these steps.
First, set the deformable convolution kernel to 1 in FDSC modules and you can obtain deformed features with 80*80 resolution.
Second, visualize these features.

**Comment by Fyzjym** [comment]
Thanks a lot. It really work
