### ISSUE TITLE
Request the character.txt & your CHARACTERSIZE setting

### ISSUE THREAD

**Issue by songquanpeng** [ecnuycxie/DG-Font#23]
Hello, will you share the character.txt, the setting `CHARACTERSIZE` and the exact font name that was used to generate your train & test data? It will be much helpful for reproducing the results reported in the paper. 

Thanks in advance.

**Comment by ecnuycxie** [comment]
For the character.txt, please refer to #8. The CHARACTERSIZE is set to 50 for images with 80*80 resolution.  Due to the constrain of copyright, we cannot provide the fonts in issues.

**Comment by songquanpeng** [comment]
Thx for your reply. I don't need the ttf files, the font name list is enough.
