### ISSUE TITLE
数据集的制作与格式问题请教

### ISSUE THREAD

**Issue by jingmingtao** [ecnuycxie/DG-Font#50]
您好，请问下咱们的数据集是怎么组成的。
1、数据集中都是一个字一张图片还是连续的多个字一张图呢，图片是普通的三通道就可以对吗，不需要标签对吗
2、能否给个数据集的例子，一两张图片就可以那样，也不会涉及商业机密，我自己制作。

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/222873162-012a80a0-1af9-492b-8928-a8283c3efc1b.png)
font1与font2分别放着不同的风格的字体对吧，可以问一下一类多少个字（多少数据）比较合适呢？

**Comment by jingmingtao** [comment]
制作的时候一张图片分辨率大小是80x80比较合适吗

**Comment by ecnuycxie** [comment]
图像采用一图一字的形式，具体生成代码可以在code中找到。在我自己的实验中，--img_size=80 --chara_size=50。

**Comment by jingmingtao** [comment]
执行这个指令对吗python font2img.py --ttf_path ttf_folder --chara character.txt --save_path save_folder --img_size 80 --chara_size CHARACTERSIZE，请问--ttf_path下文件夹放的是自己从网上下载的字体吗，我看着是ttf格式的对吗

**Comment by jingmingtao** [comment]
也就是说我先从网上下载字体，其格式为ttf，然后使用python font2img.py来转换成img对吗

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/223305961-ad3a15cb-c70e-4679-9431-2d4f7a044dd7.png)
打印是0说明我没有字体，意思是我要先下载好ttf格式的字体文件放到--ttf_path ttf_folder下边对吗
