### ISSUE TITLE
测试结果请教

### ISSUE THREAD

**Issue by jingmingtao** [ecnuycxie/DG-Font#58]
您好，我现在遇到疑问，可以问一下测试的下图哪个是风格参考图，哪个是内容参考图吗，哪个是模型生成的吗，真的求求您的指导了。
第一行是内容，左边第一列是风格吗，求求了，万分感谢
![0_RNDEMA_22_10](https://user-images.githubusercontent.com/114384977/224916694-94516e21-eb20-4ff4-8db1-e15c68e03ac7.jpg)

**Comment by yinminzzy** [comment]
请教一下DCN如何安装？

**Comment by wujiekd** [comment]
兄弟 你怎么生成字体的，你用的是单卡还是多卡呀，loss有没有变负啊，batchsize设置的多少呀，我怎么复现结果特别差
![image](https://user-images.githubusercontent.com/49955700/227837837-de180a77-539e-4775-ab80-5b4a33530938.png)

**Comment by jingmingtao** [comment]
我的效果也很差阿，你看看论文里他们效果多么好，我这是条了一个好的这个样子

**Comment by jingmingtao** [comment]
> 请教一下DCN如何安装？

就安装教程推荐的就可以，pytorch1.7就可以阿

**Comment by jingmingtao** [comment]
> 兄弟 你怎么生成字体的，你用的是单卡还是多卡呀，loss有没有变负啊，batchsize设置的多少呀，我怎么复现结果特别差 ![image](https://user-images.githubusercontent.com/49955700/227837837-de180a77-539e-4775-ab80-5b4a33530938.png)

我的loss也变成了负数阿，你解决了吗，是更换了dcn版本吗，你更换的版本是什么
