### ISSUE TITLE
How to visualize offset as the figure 7 in your paper

### ISSUE THREAD

**Issue by sunnyHelen** [ecnuycxie/DG-Font#6]
As I know, the offset of DCN is a high-dimension feature, how do you visualize the offset as the fig 7 in your paper~

**Comment by ecnuycxie** [comment]
As stated in the paper ". To visualize the offsets clearly, the kernel of deformable convolution in the FDSC module is set to 1×1.As demonstrated in Fig. 7". When the kernel is set to 1, we can obtain a learned offset map with a size of IMAGESIZE*IMAGESIZE.

**Comment by ecnuycxie** [comment]
@sunnyHelen 
 As stated in the paper ". To visualize the offsets clearly, the kernel of deformable convolution in the FDSC module is set to 1×1.As demonstrated in Fig. 7". When the kernel is set to 1, we can obtain a learned offset map with a size of IMAGESIZE*IMAGESIZE.

**Comment by ecnuycxie** [comment]
@sunnyHelen
As stated in the paper ". To visualize the offsets clearly, the kernel of deformable convolution in the FDSC module is set to 1×1.As demonstrated in Fig. 7". When the kernel is set to 1, we can obtain a learned offset map with a size of IMAGESIZE*IMAGESIZE.
