### ISSUE TITLE
loss is negative！！

### ISSUE THREAD

**Issue by wujiekd** [ecnuycxie/DG-Font#63]
![image](https://user-images.githubusercontent.com/49955700/227838196-8db53c51-f181-40a8-9c02-13c0fa14c571.png)

Result：
![image](https://user-images.githubusercontent.com/49955700/227838240-4ea93e57-d782-4292-bb33-1779c4aacbe4.png)

**Comment by wujiekd** [comment]
Is it OK for DCN to have this error?

![image](https://user-images.githubusercontent.com/49955700/227841575-7c386427-2341-4d5b-b265-1bb555fc3a2e.png)

**Comment by jingmingtao** [comment]
我的也是出现了这种情况，你解决了没有？可能作者比较忙，我有好多问题都不提了，提问了也不会回答一般

**Comment by jingmingtao** [comment]
查阅资料，有可能是loss没有设置下限，数据有问题。但是ganloss有负数有的这么说。

**Comment by jingmingtao** [comment]
而且你的测试图跟我一样基本就是效果很差，尤其越训练越差，一开始有些还可以的，也不太行，不知道咋办，你有什么见解吗

**Comment by wujiekd** [comment]
我已经解决了，应该是DCN版本没安装好
