### ISSUE TITLE
训练的相关问题

### ISSUE THREAD

**Issue by zi1zi** [ecnuycxie/DG-Font#70]
![image](https://github.com/ecnuycxie/DG-Font/assets/48040139/86d2f62f-d751-4bd5-8fec-93648f606e32)
1.我使用这两种字体作为训练的数据集，其他都是默认配置，训练的命令python main.py --gpu 0 --img_size 80 --data_path ../data --output_k 2 --batch_size 8 --val_num 190，但是一百多轮次以后出现了过拟合（我个人认为的），如图所示
![image](https://github.com/ecnuycxie/DG-Font/assets/48040139/98336d51-d4e2-4597-bb31-2dba3599187d)
但是之前轮次的效果也不怎么好，如图
![image](https://github.com/ecnuycxie/DG-Font/assets/48040139/cc9d13c2-1b61-4d38-a292-4e9f03a9159c)
![image](https://github.com/ecnuycxie/DG-Font/assets/48040139/460d4354-ff00-4862-9782-0d8ce276ac97)
![image](https://github.com/ecnuycxie/DG-Font/assets/48040139/2fa53466-d948-45d0-a6d0-0ef532a97026)
请问为什么会出现这种情况呀？

**Comment by ecnuycxie** [comment]
两种字体还不足以让模型学习到有用的分布，建议把你需要生成的字体加入比较大的数据集一起训练。

**Comment by zi1zi** [comment]
感谢您的回复，您的意思是训练集应包括更多的字体种类，是吗？
如果是，那应该至少是几种字体呢
