### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by lzy1126** [ecnuycxie/DG-Font#81]
Thanks for the code, it's easy to ask if there are versions of pytorch, cuda, and python

**Comment by yueyuemoon** [comment]
你好，请问你复现成功了吗？我出现了一直找不到数据集的问题，但文件夹下是存在图片的。

**Comment by lzy1126** [comment]
你的main.py中出现的args.att_to_use = {1，2，3.。。。。。。}改成了args.att_to_use = [i for i in range（args.num_cls）]吗

**Comment by yueyuemoon** [comment]
改了的，我开始刚开始训练的时候数据集用的比较少，只是把类别往少了改，没有像你这样改了语句
