### ISSUE TITLE
Discriminator判别器问题

### ISSUE THREAD

**Issue by clscy** [ecnuycxie/DG-Font#9]
你好，为什么Discriminator计算过程中out = self.main(x)出来的维度是batch_size*output_k*2*2，而不是batch_size*output_k*1*1？

**Comment by ecnuycxie** [comment]
hello, @clscy . In my experiments, i noticed that ignoring some features in the penultimate layer will slightly improve the performance. If you want to make full use of the output features, you only need to set the kernel of last convolution layer to 5 .
